import express from "express";
import router from "./route/route";
import errorMiddleware from "./middleware/error-handler";
import notFoundMiddleware from "./middleware/not-found";
const app = express();
app.use(router);
app.use(notFoundMiddleware);
app.use(errorMiddleware);
export default app;
// app.listen(process.env.PORT || 3000);
